import {
    ApplicationCommandType,
    PermissionFlagsBits,
    PermissionsBitField,
    RESTPostAPIChatInputApplicationCommandsJSONBody,
    RESTPostAPIContextMenuApplicationCommandsJSONBody,
} from 'discord.js';

import { Args } from './index.js';
import { Language } from '../models/enum-helpers/index.js';
import { Lang } from '../services/index.js';

export const ChatCommandMetadata: {
    [command: string]: RESTPostAPIChatInputApplicationCommandsJSONBody;
} = {
    DEV: {
        type: ApplicationCommandType.ChatInput,
        name: Lang.getRef('chatCommands.dev', Language.Default),
        name_localizations: Lang.getRefLocalizationMap('chatCommands.dev'),
        description: Lang.getRef('commandDescs.dev', Language.Default),
        description_localizations: Lang.getRefLocalizationMap('commandDescs.dev'),
        dm_permission: true,
        default_member_permissions: PermissionsBitField.resolve([
            PermissionFlagsBits.Administrator,
        ]).toString(),
        options: [
            {
                ...Args.DEV_COMMAND,
                required: true,
            },
        ],
    },
    HELP: {
        type: ApplicationCommandType.ChatInput,
        name: Lang.getRef('chatCommands.help', Language.Default),
        name_localizations: Lang.getRefLocalizationMap('chatCommands.help'),
        description: Lang.getRef('commandDescs.help', Language.Default),
        description_localizations: Lang.getRefLocalizationMap('commandDescs.help'),
        dm_permission: true,
        default_member_permissions: undefined,
        options: [
            {
                ...Args.HELP_OPTION,
                required: true,
            },
        ],
    },
    INFO: {
        type: ApplicationCommandType.ChatInput,
        name: Lang.getRef('chatCommands.info', Language.Default),
        name_localizations: Lang.getRefLocalizationMap('chatCommands.info'),
        description: Lang.getRef('commandDescs.info', Language.Default),
        description_localizations: Lang.getRefLocalizationMap('commandDescs.info'),
        dm_permission: true,
        default_member_permissions: undefined,
        options: [
            {
                ...Args.INFO_OPTION,
                required: true,
            },
        ],
    },
    TEST: {
        type: ApplicationCommandType.ChatInput,
        name: Lang.getRef('chatCommands.test', Language.Default),
        name_localizations: Lang.getRefLocalizationMap('chatCommands.test'),
        description: Lang.getRef('commandDescs.test', Language.Default),
        description_localizations: Lang.getRefLocalizationMap('commandDescs.test'),
        dm_permission: true,
        default_member_permissions: undefined,
    },
    BAN: {
        type: ApplicationCommandType.ChatInput,
        name: Lang.getRef('chatCommands.ban', Language.Default),
        name_localizations: Lang.getRefLocalizationMap('chatCommands.ban'),
        description: Lang.getRef('commandDescs.ban', Language.Default),
        description_localizations: Lang.getRefLocalizationMap('commandDescs.ban'),
        dm_permission: false,
        default_member_permissions: PermissionsBitField.resolve([
            PermissionFlagsBits.BanMembers,
        ]).toString(),
        options: [
            {
                name: Lang.getRef('arguments.user', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.user'),
                description: Lang.getRef('argDescs.banUser', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.banUser'),
                type: ApplicationCommandOptionType.User,
                required: true,
            },
            {
                name: Lang.getRef('arguments.reason', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.reason'),
                description: Lang.getRef('argDescs.banReason', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.banReason'),
                type: ApplicationCommandOptionType.String,
                required: false,
                max_length: 512,
            },
            {
                name: Lang.getRef('arguments.deleteDays', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.deleteDays'),
                description: Lang.getRef('argDescs.deleteDays', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.deleteDays'),
                type: ApplicationCommandOptionType.Integer,
                required: false,
                min_value: 0,
                max_value: 7,
            },
        ],
    },
    UNBAN: {
        type: ApplicationCommandType.ChatInput,
        name: Lang.getRef('chatCommands.unban', Language.Default),
        name_localizations: Lang.getRefLocalizationMap('chatCommands.unban'),
        description: Lang.getRef('commandDescs.unban', Language.Default),
        description_localizations: Lang.getRefLocalizationMap('commandDescs.unban'),
        dm_permission: false,
        default_member_permissions: PermissionsBitField.resolve([
            PermissionFlagsBits.BanMembers,
        ]).toString(),
        options: [
            {
                name: Lang.getRef('arguments.userId', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.userId'),
                description: Lang.getRef('argDescs.unbanUserId', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.unbanUserId'),
                type: ApplicationCommandOptionType.String,
                required: true,
                min_length: 17,
                max_length: 20,
            },
            {
                name: Lang.getRef('arguments.reason', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.reason'),
                description: Lang.getRef('argDescs.unbanReason', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.unbanReason'),
                type: ApplicationCommandOptionType.String,
                required: false,
                max_length: 512,
            },
        ],
    },
    KICK: {
        type: ApplicationCommandType.ChatInput,
        name: Lang.getRef('chatCommands.kick', Language.Default),
        name_localizations: Lang.getRefLocalizationMap('chatCommands.kick'),
        description: Lang.getRef('commandDescs.kick', Language.Default),
        description_localizations: Lang.getRefLocalizationMap('commandDescs.kick'),
        dm_permission: false,
        default_member_permissions: PermissionsBitField.resolve([
            PermissionFlagsBits.KickMembers,
        ]).toString(),
        options: [
            {
                name: Lang.getRef('arguments.user', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.user'),
                description: Lang.getRef('argDescs.kickUser', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.kickUser'),
                type: ApplicationCommandOptionType.User,
                required: true,
            },
            {
                name: Lang.getRef('arguments.reason', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.reason'),
                description: Lang.getRef('argDescs.kickReason', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.kickReason'),
                type: ApplicationCommandOptionType.String,
                required: true,
                max_length: 512,
            },
        ],
    },
    MUTE: {
        type: ApplicationCommandType.ChatInput,
        name: Lang.getRef('chatCommands.mute', Language.Default),
        name_localizations: Lang.getRefLocalizationMap('chatCommands.mute'),
        description: Lang.getRef('commandDescs.mute', Language.Default),
        description_localizations: Lang.getRefLocalizationMap('commandDescs.mute'),
        dm_permission: false,
        default_member_permissions: PermissionsBitField.resolve([
            PermissionFlagsBits.ModerateMembers,
        ]).toString(),
        options: [
            {
                name: Lang.getRef('arguments.user', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.user'),
                description: Lang.getRef('argDescs.muteUser', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.muteUser'),
                type: ApplicationCommandOptionType.User,
                required: true,
            },
            {
                name: Lang.getRef('arguments.duration', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.duration'),
                description: Lang.getRef('argDescs.muteDuration', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.muteDuration'),
                type: ApplicationCommandOptionType.String,
                required: true,
                min_length: 2,
                max_length: 32,
            },
            {
                name: Lang.getRef('arguments.reason', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.reason'),
                description: Lang.getRef('argDescs.muteReason', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.muteReason'),
                type: ApplicationCommandOptionType.String,
                required: false,
                max_length: 512,
            },
        ],
    },
    UNMUTE: {
        type: ApplicationCommandType.ChatInput,
        name: Lang.getRef('chatCommands.unmute', Language.Default),
        name_localizations: Lang.getRefLocalizationMap('chatCommands.unmute'),
        description: Lang.getRef('commandDescs.unmute', Language.Default),
        description_localizations: Lang.getRefLocalizationMap('commandDescs.unmute'),
        dm_permission: false,
        default_member_permissions: PermissionsBitField.resolve([
            PermissionFlagsBits.ModerateMembers,
        ]).toString(),
        options: [
            {
                name: Lang.getRef('arguments.user', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.user'),
                description: Lang.getRef('argDescs.unmuteUser', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.unmuteUser'),
                type: ApplicationCommandOptionType.User,
                required: true,
            },
            {
                name: Lang.getRef('arguments.reason', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.reason'),
                description: Lang.getRef('argDescs.unmuteReason', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.unmuteReason'),
                type: ApplicationCommandOptionType.String,
                required: false,
                max_length: 512,
            },
        ],
    },
    TIMEOUT: {
        type: ApplicationCommandType.ChatInput,
        name: Lang.getRef('chatCommands.timeout', Language.Default),
        name_localizations: Lang.getRefLocalizationMap('chatCommands.timeout'),
        description: Lang.getRef('commandDescs.timeout', Language.Default),
        description_localizations: Lang.getRefLocalizationMap('commandDescs.timeout'),
        dm_permission: false,
        default_member_permissions: PermissionsBitField.resolve([
            PermissionFlagsBits.ModerateMembers,
        ]).toString(),
        options: [
            {
                name: Lang.getRef('arguments.user', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.user'),
                description: Lang.getRef('argDescs.timeoutUser', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.timeoutUser'),
                type: ApplicationCommandOptionType.User,
                required: true,
            },
            {
                name: Lang.getRef('arguments.duration', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.duration'),
                description: Lang.getRef('argDescs.timeoutDuration', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.timeoutDuration'),
                type: ApplicationCommandOptionType.String,
                required: true,
                min_length: 2,
                max_length: 32,
            },
            {
                name: Lang.getRef('arguments.reason', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.reason'),
                description: Lang.getRef('argDescs.timeoutReason', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.timeoutReason'),
                type: ApplicationCommandOptionType.String,
                required: false,
                max_length: 512,
            },
        ],
    },
    WARN: {
        type: ApplicationCommandType.ChatInput,
        name: Lang.getRef('chatCommands.warn', Language.Default),
        name_localizations: Lang.getRefLocalizationMap('chatCommands.warn'),
        description: Lang.getRef('commandDescs.warn', Language.Default),
        description_localizations: Lang.getRefLocalizationMap('commandDescs.warn'),
        dm_permission: false,
        default_member_permissions: PermissionsBitField.resolve([
            PermissionFlagsBits.ModerateMembers,
        ]).toString(),
        options: [
            {
                name: Lang.getRef('arguments.user', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.user'),
                description: Lang.getRef('argDescs.warnUser', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.warnUser'),
                type: ApplicationCommandOptionType.User,
                required: true,
            },
            {
                name: Lang.getRef('arguments.reason', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.reason'),
                description: Lang.getRef('argDescs.warnReason', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.warnReason'),
                type: ApplicationCommandOptionType.String,
                required: true,
                max_length: 512,
            },
        ],
    },
    WARNINGS: {
        type: ApplicationCommandType.ChatInput,
        name: Lang.getRef('chatCommands.warnings', Language.Default),
        name_localizations: Lang.getRefLocalizationMap('chatCommands.warnings'),
        description: Lang.getRef('commandDescs.warnings', Language.Default),
        description_localizations: Lang.getRefLocalizationMap('commandDescs.warnings'),
        dm_permission: false,
        default_member_permissions: PermissionsBitField.resolve([
            PermissionFlagsBits.ModerateMembers,
        ]).toString(),
        options: [
            {
                name: Lang.getRef('arguments.user', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.user'),
                description: Lang.getRef('argDescs.warningsUser', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.warningsUser'),
                type: ApplicationCommandOptionType.User,
                required: true,
            },
            {
                name: Lang.getRef('arguments.page', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.page'),
                description: Lang.getRef('argDescs.page', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.page'),
                type: ApplicationCommandOptionType.Integer,
                required: false,
                min_value: 1,
            },
        ],
    },
    CLEAR: {
        type: ApplicationCommandType.ChatInput,
        name: Lang.getRef('chatCommands.clear', Language.Default),
        name_localizations: Lang.getRefLocalizationMap('chatCommands.clear'),
        description: Lang.getRef('commandDescs.clear', Language.Default),
        description_localizations: Lang.getRefLocalizationMap('commandDescs.clear'),
        dm_permission: false,
        default_member_permissions: PermissionsBitField.resolve([
            PermissionFlagsBits.ManageMessages,
        ]).toString(),
        options: [
            {
                name: Lang.getRef('arguments.amount', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.amount'),
                description: Lang.getRef('argDescs.clearAmount', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.clearAmount'),
                type: ApplicationCommandOptionType.Integer,
                required: true,
                min_value: 1,
                max_value: 100,
            },
            {
                name: Lang.getRef('arguments.user', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.user'),
                description: Lang.getRef('argDescs.clearUser', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.clearUser'),
                type: ApplicationCommandOptionType.User,
                required: false,
            },
        ],
    },
    LOCK: {
        type: ApplicationCommandType.ChatInput,
        name: Lang.getRef('chatCommands.lock', Language.Default),
        name_localizations: Lang.getRefLocalizationMap('chatCommands.lock'),
        description: Lang.getRef('commandDescs.lock', Language.Default),
        description_localizations: Lang.getRefLocalizationMap('commandDescs.lock'),
        dm_permission: false,
        default_member_permissions: PermissionsBitField.resolve([
            PermissionFlagsBits.ManageChannels,
        ]).toString(),
        options: [
            {
                ...Args.LOCK_ACTION,
                required: true,
            },
            {
                name: Lang.getRef('arguments.channel', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.channel'),
                description: Lang.getRef('argDescs.lockChannel', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.lockChannel'),
                type: ApplicationCommandOptionType.Channel,
                channel_types: [0, 5],
                required: false,
            },
            {
                name: Lang.getRef('arguments.reason', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.reason'),
                description: Lang.getRef('argDescs.lockReason', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.lockReason'),
                type: ApplicationCommandOptionType.String,
                required: false,
                max_length: 512,
            },
        ],
    },
    SLOWMODE: {
        type: ApplicationCommandType.ChatInput,
        name: Lang.getRef('chatCommands.slowmode', Language.Default),
        name_localizations: Lang.getRefLocalizationMap('chatCommands.slowmode'),
        description: Lang.getRef('commandDescs.slowmode', Language.Default),
        description_localizations: Lang.getRefLocalizationMap('commandDescs.slowmode'),
        dm_permission: false,
        default_member_permissions: PermissionsBitField.resolve([
            PermissionFlagsBits.ManageChannels,
        ]).toString(),
        options: [
            {
                name: Lang.getRef('arguments.channel', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.channel'),
                description: Lang.getRef('argDescs.slowmodeChannel', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.slowmodeChannel'),
                type: ApplicationCommandOptionType.Channel,
                channel_types: [0, 5],
                required: false,
            },
            {
                name: Lang.getRef('arguments.duration', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.duration'),
                description: Lang.getRef('argDescs.slowmodeDuration', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.slowmodeDuration'),
                type: ApplicationCommandOptionType.String,
                required: true,
                min_length: 1,
                max_length: 32,
            },
            {
                name: Lang.getRef('arguments.reason', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.reason'),
                description: Lang.getRef('argDescs.slowmodeReason', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.slowmodeReason'),
                type: ApplicationCommandOptionType.String,
                required: false,
                max_length: 512,
            },
        ],
    },
    NICK: {
        type: ApplicationCommandType.ChatInput,
        name: Lang.getRef('chatCommands.nick', Language.Default),
        name_localizations: Lang.getRefLocalizationMap('chatCommands.nick'),
        description: Lang.getRef('commandDescs.nick', Language.Default),
        description_localizations: Lang.getRefLocalizationMap('commandDescs.nick'),
        dm_permission: false,
        default_member_permissions: PermissionsBitField.resolve([
            PermissionFlagsBits.ManageNicknames,
        ]).toString(),
        options: [
            {
                name: Lang.getRef('arguments.user', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.user'),
                description: Lang.getRef('argDescs.nickUser', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.nickUser'),
                type: ApplicationCommandOptionType.User,
                required: true,
            },
            {
                name: Lang.getRef('arguments.nickname', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.nickname'),
                description: Lang.getRef('argDescs.nickName', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.nickName'),
                type: ApplicationCommandOptionType.String,
                required: true,
                max_length: 32,
            },
            {
                name: Lang.getRef('arguments.reason', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.reason'),
                description: Lang.getRef('argDescs.nickReason', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.nickReason'),
                type: ApplicationCommandOptionType.String,
                required: false,
                max_length: 512,
            },
        ],
    },
    ROLE: {
        type: ApplicationCommandType.ChatInput,
        name: Lang.getRef('chatCommands.role', Language.Default),
        name_localizations: Lang.getRefLocalizationMap('chatCommands.role'),
        description: Lang.getRef('commandDescs.role', Language.Default),
        description_localizations: Lang.getRefLocalizationMap('commandDescs.role'),
        dm_permission: false,
        default_member_permissions: PermissionsBitField.resolve([
            PermissionFlagsBits.ManageRoles,
        ]).toString(),
        options: [
            {
                ...Args.ROLE_ACTION,
                required: true,
            },
            {
                name: Lang.getRef('arguments.user', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.user'),
                description: Lang.getRef('argDescs.roleUser', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.roleUser'),
                type: ApplicationCommandOptionType.User,
                required: true,
            },
            {
                name: Lang.getRef('arguments.role', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.role'),
                description: Lang.getRef('argDescs.roleRole', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.roleRole'),
                type: ApplicationCommandOptionType.Role,
                required: true,
            },
            {
                name: Lang.getRef('arguments.reason', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.reason'),
                description: Lang.getRef('argDescs.roleReason', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.roleReason'),
                type: ApplicationCommandOptionType.String,
                required: false,
                max_length: 512,
            },
        ],
    },
    MODLOG: {
        type: ApplicationCommandType.ChatInput,
        name: Lang.getRef('chatCommands.modlog', Language.Default),
        name_localizations: Lang.getRefLocalizationMap('chatCommands.modlog'),
        description: Lang.getRef('commandDescs.modlog', Language.Default),
        description_localizations: Lang.getRefLocalizationMap('commandDescs.modlog'),
        dm_permission: false,
        default_member_permissions: PermissionsBitField.resolve([
            PermissionFlagsBits.ModerateMembers,
        ]).toString(),
        options: [
            {
                name: Lang.getRef('arguments.user', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.user'),
                description: Lang.getRef('argDescs.modlogUser', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.modlogUser'),
                type: ApplicationCommandOptionType.User,
                required: true,
            },
            {
                name: Lang.getRef('arguments.page', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.page'),
                description: Lang.getRef('argDescs.page', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.page'),
                type: ApplicationCommandOptionType.Integer,
                required: false,
                min_value: 1,
            },
        ],
    },
    CASE: {
        type: ApplicationCommandType.ChatInput,
        name: Lang.getRef('chatCommands.case', Language.Default),
        name_localizations: Lang.getRefLocalizationMap('chatCommands.case'),
        description: Lang.getRef('commandDescs.case', Language.Default),
        description_localizations: Lang.getRefLocalizationMap('commandDescs.case'),
        dm_permission: false,
        default_member_permissions: PermissionsBitField.resolve([
            PermissionFlagsBits.ModerateMembers,
        ]).toString(),
        options: [
            {
                name: Lang.getRef('arguments.caseId', Language.Default),
                name_localizations: Lang.getRefLocalizationMap('arguments.caseId'),
                description: Lang.getRef('argDescs.caseId', Language.Default),
                description_localizations: Lang.getRefLocalizationMap('argDescs.caseId'),
                type: ApplicationCommandOptionType.Integer,
                required: true,
                min_value: 1,
            },
        ],
    },
};

export const MessageCommandMetadata: {
    [command: string]: RESTPostAPIContextMenuApplicationCommandsJSONBody;
} = {
    VIEW_DATE_SENT: {
        type: ApplicationCommandType.Message,
        name: Lang.getRef('messageCommands.viewDateSent', Language.Default),
        name_localizations: Lang.getRefLocalizationMap('messageCommands.viewDateSent'),
        default_member_permissions: undefined,
        dm_permission: true,
    },
};

export const UserCommandMetadata: {
    [command: string]: RESTPostAPIContextMenuApplicationCommandsJSONBody;
} = {
    VIEW_DATE_JOINED: {
        type: ApplicationCommandType.User,
        name: Lang.getRef('userCommands.viewDateJoined', Language.Default),
        name_localizations: Lang.getRefLocalizationMap('userCommands.viewDateJoined'),
        default_member_permissions: undefined,
        dm_permission: true,
    },
};
